### ISSUE TITLE
Download Claim Issue, poet-js isValidClaim

### ISSUE THREAD

**Issue by kennylavender** [poetapp/node#144]
Possible issue with the nodes usage of `isValidClaim` from poet-js, it was introduced in #136

I keep getting this error during the downloading of claims:

```
[2018-06-12T05:00:49.268Z] ERROR: claim.dateCreated.getTime is not a function
```

It seems to be from calling the method `getTime` on a string instead of a date object.

I checked the tests in poet-js and `isValidClaim` expects a claims `dateCreated` property to be a date object, not a string.

This is blocking #20, #142

**Comment by geoffturk** [comment]
I'm reassigning to Jesse. @jwicks31 - please have a look and try to resolve.

**Comment by lautarodragan** [comment]
I merged master into my branch today :man_facepalming: 

Seeing same behavior.

Blocking https://github.com/poetapp/node/pull/145

**Comment by lautarodragan** [comment]
Adding the full stack trace:

```
        "TypeError: claim.dateCreated.getTime is not a function",
        "    at claimToProto (/home/taro/Projects/poet/node/node_modules/@po.et/poet-js/dist/babel/src/Serialization.js:27:44)",
        "    at Object.claimToHex (/home/taro/Projects/poet/node/node_modules/@po.et/poet-js/dist/babel/src/Serialization.js:34:57)",
        "    at getClaimId (/home/taro/Projects/poet/node/node_modules/@po.et/poet-js/dist/babel/src/Claim.js:10:62)",
        "    at Object.exports.isValidClaim (/home/taro/Projects/poet/node/node_modules/@po.et/poet-js/dist/babel/src/Claim.js:46:100)",
        "    at ClaimController.downloadEntryClaim (/home/taro/Projects/poet/node/dist/babel/src/Storage/ClaimController.js:106:28)",
        "    at <anonymous>",
        "    at process._tickCallback (internal/process/next_tick.js:182:7)"
```

**Comment by lautarodragan** [comment]
The underlying issue is that `isClaim` doesn't check that there's a dateCreated property on the claim and that it is a Date object.
